### ISSUE TITLE
handling non existing gets to defaut zero cathing throw

### ISSUE THREAD

**Issue by superbem** [emilk/Configuru#2]
#define getjs2(op,jsout){try{op=(decltype(op))( jsout );}catch(...){op=0;}}

ex
float op;
getjs2(op,someconfiguru,["one"]["two"]);

You could implement this better with an = method operator

Cheers and thanks

**Comment by emilk** [comment]
Resolved in d8fba7a4232e5a4ddaad5313868b267266b05e63:

``` C++
float op = someconfiguru.get_or({"one", "two"}, 0.0f);
```
